version: "3"

services:
  nginx:
    container_name: "nginx"
    build:
      dockerfile: "./container/nginx/Dockerfile"
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html

  web:
    container_name: "web"
    build:
      dockerfile: "./container/web/Dockerfile"
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
